src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use App\Repository\FortuneCookieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 20)]
    private ?string $iconKey = null;

    //el fetch:EXTRA_LAZY modificara nuestra consulta como select count(*) from
    //si no lo ponemos la consulta de nuestra página principal sera un select con
    //todos los campos de la entidad FortuneCookie
    #[ORM\OneToMany(mappedBy: 'category', targetEntity: FortuneCookie::class, fetch: 'EXTRA_LAZY')]
    private Collection $fortuneCookies;

    public function __construct()
    {
        $this->fortuneCookies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIconKey(): ?string
    {
        return $this->iconKey;
    }

    public function setIconKey(string $iconKey): self
    {
        $this->iconKey = $iconKey;

        return $this;
    }

    /**
     * @return Collection<int, FortuneCookie>
     */
    public function getFortuneCookies(): Collection
    {
        return $this->fortuneCookies;
    }
    public function getFortuneCookiesStillInProduction(): Collection{
        $criteria = FortuneCookieRepository::createFortuneCookiesStillInProductionCriteria();
        //para poder usarla usamos el matching, los objetos Criteria no hacen consultas asi que
        //el metodo puedes ser estático
        return $this->fortuneCookies->matching($criteria);
    }

    public function addFortuneCookie(FortuneCookie $fortuneCookie): self
    {
        if (!$this->fortuneCookies->contains($fortuneCookie)) {
            $this->fortuneCookies->add($fortuneCookie);
            $fortuneCookie->setCategory($this);
        }

        return $this;
    }

    public function removeFortuneCookie(FortuneCookie $fortuneCookie): self
    {
        if ($this->fortuneCookies->removeElement($fortuneCookie)) {
            // set the owning side to null (unless already changed)
            if ($fortuneCookie->getCategory() === $this) {
                $fortuneCookie->setCategory(null);
            }
        }

        return $this;
    }
}

src/Controller/FortuneController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\FortuneCookie;
use App\Model\CategoryFortuneStats;
use App\Repository\CategoryRepository;
use App\Repository\FortuneCookieRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FortuneController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function index(Request $request,CategoryRepository $categoryRepository): Response
    {
        //findBy([],['name' => 'ASC']); el segundo parametro [] de esta consulta se basa en el orden por ejemplo asc o desc
        //el primero es para encontrar uno en especifico, vamos bien el criterio
        //al find (a secas) hay que pasarle un int pero debe ser como variable
        //en el base.html.twig el form tiene un name q, entonces si el valor no es null se metera en el if
        $searchTerm = $request->query->get('q');
        if ($searchTerm){
            $categories = $categoryRepository->search($searchTerm);
        }
        else{
            $categories = $categoryRepository->findAllOrdered();
//            $categories = $categoryRepository->findBy(['name' =>['Job', 'Love']], ['name' => 'ASC']);
//            $categories = $categoryRepository->findBy(['name' =>'Job','id' =>'1'], ['name' => 'ASC']);

        }
        return $this->render('fortune/homepage.html.twig',[
            'categories' => $categories
        ]);
    }

    /**
     * @throws NonUniqueResultException
     * @throws NoResultException
     */
    #[Route('/category/{id}', name: 'app_category_show')]
    public function showCategory(int $id, FortuneCookieRepository $fortuneCookie, CategoryRepository $categoryRepository): Response
    {
        /* return $this->render('fortune/showCategory.html.twig',[
            'category' => $category,
            'fortunesPrinted' => $result['fortunesPrinted'],
            'fortunesAverage' => $result['fortunesAverage']
            ahora en el showCategory.twig solamente tendria que
            poner {{ fortunesPrinted }}

        ]);*/
        $category = $categoryRepository->findWithFortunesJoin($id);
        $result = $fortuneCookie->countFortuneCookieModelAvg($category);
        //accedemos a las propiedades que tiene nuestro model
        return $this->render('fortune/showCategory.html.twig',[
            'category' => $category,
//             para el model categoryFortuneStats se puede acceder a sus propiedades asi pero
                //el metodo countFortune deberia devolver un objeto CategoryFortunesStats
            'fortunePrinted' => $result->fortunePrinted,
            'fortuneAverage' => $result->fortuneAverage,
//            'result' => $result
        ]);
    }
}

templates/fortune/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1 class="text-center my-8 text-2xl text-slate-800 font-bold">Query for your Fortune</h1>
<p class="text-center">Review categories for available cookie fortunes</p>
<div class="xl:container xl:mx-auto grid grid-cols-2 gap-6 px-10 mt-8 mb-10">
    {% for categoryData in categories %}
        {% set category = categoryData[0] %}
        <a class="bg-orange-300 hover:bg-orange-300 text-white text-center rounded-full p-4" href="{{ path('app_category_show', {'id':  category.id}) }}">
            {# el length es el count #}
            <span class="fa {{ category.iconKey }}"></span> <span class="font-bold text-lg">{{ category.name }}</span>  ({{ categoryData.fortuneCookiesTotal }})
        </a>
    {% else %}
        <h3>Hmm... there don't seem to be any fortunes</h3>
    {% endfor %}
</div>
{% endblock %}

templates/fortune/showCategory.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    
        
<h1 class="text-3xl p-5 text-center my-4 font-semibold"><span class="fa {{ category.iconKey }}"></span> {{ category.name }} Fortunes</h1>
<div class="flex justify-center mb-16 px-4">
    <div>
        <table class="table-auto border mb-6">
            <thead class="bg-slate-500 text-white">
                <tr>
                    <th class="border p-4">
                        Fortunes ({{ fortunePrinted|number_format }} total
                        {{ fortuneAverage|number_format }} average)
{#                        {{ result.categoryName }}#}
                    </th>
                    <th class="border p-4">
                        Print History
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for fortuneCookie in category.fortuneCookiesStillInProduction %}
                <tr class="hover:bg-slate-200">
                    <td class="border p-4">
                        {{ fortuneCookie.fortune }}
                    </td>
                    <td class="border p-4">
                        {{ fortuneCookie.numberPrinted }} printed since {{ fortuneCookie.createdAt|date('M jS Y') }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a class="text-slate-700 hover:text-slate-900 font-semibold" href="{{ path('app_homepage') }}"><i class="fa fa-angle-double-left"></i> Back to Fortune Categories</a>
    </div>
</div>
    
        
    
{% endblock %}